# Generated by Django 5.1 on 2024-10-23 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction_listings',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
