# Generated by Django 5.1 on 2024-10-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bids_comments_auction_listings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction_listings',
            name='price',
        ),
        migrations.AddField(
            model_name='auction_listings',
            name='startingbid',
            field=models.DecimalField(decimal_places=2, default=100, max_digits=10),
            preserve_default=False,
        ),
    ]
